spring:
  application:
    name: consumer
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

server:
  port: 8888


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
    enabled: true
    fetch-registry: true

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: true
    retryableStatusCodes: 500