server:
    port: 8083
spring:
    application:
        name: provider
    cloud:
      client:
        ipAddress: 192:168:43:177
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/